# Generated by Django 5.0.4 on 2024-04-29 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('MCQ', 'Multiple Choice'), ('CHECKBOX', 'Checkbox')], max_length=10)),
                ('choices', models.TextField(blank=True, help_text='Enter choices separated by commas. Only required for MCQ and Checkbox type questions.', null=True)),
                ('answer', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField(default=30, help_text='Duration in seconds')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], max_length=10)),
                ('first_runner_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_runner_up', to=settings.AUTH_USER_MODEL)),
                ('second_runner_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_runner_up', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_detail', models.CharField(choices=[('WINNER', 'Winner'), ('RUNNER_UP_1', '1st Runner Up'), ('RUNNER_UP_2', '2nd Runner Up')], max_length=20)),
                ('prize_description', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='quiz.campaign')),
            ],
        ),
    ]
