# Generated by Django 5.0.4 on 2024-04-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the question. Only required for Image type questions.', null=True, upload_to='quiz_images/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('MCQ', 'Multiple Choice'), ('CHECKBOX', 'Checkbox'), ('IMAGE', 'Image')], max_length=10),
        ),
    ]
