# Generated by Django 5.0.4 on 2024-04-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_image_alter_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
