# Generated by Django 5.0.4 on 2024-04-30 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_participation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.campaign'),
            preserve_default=False,
        ),
    ]
