# Generated by Django 5.0.4 on 2024-05-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload an image for the question. Only required for Image type questions.', null=True, upload_to='profile_picture/'),
        ),
    ]
